name: Continuous Integration
on:
  push:
    branches: [nexus, v0]
  pull_request:
    branches: [nexus]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'
          cache: true
      - name: Go mod verification
        run: |
          cd backend
          go mod tidy
          git diff --exit-code go.mod go.sum
      - name: Go vet
        run: |
          cd backend
          go vet ./...
      - name: Format Go Code
        run: |
          cd backend
          gofmt -s -w .
      - name: Go fmt check
        run: |
          cd backend
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "❌ Code is not formatted. Run 'gofmt -s -w .'"
            gofmt -s -l .
            exit 1
          fi
          echo "✅ Code is formatted correctly"
      - name: Go security check
        uses: securego/gosec@master
        with:
          args: ./...
      - name: Docker compose Validation
        run: "docker compose config -q \necho \"✅ Docker compose file is valid\"\n"
